---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "v3"
    ignore:
      # Thrift version needs to match the version of the thrift-compiler used to generate code,
      # and therefore this dependency requires a more manual upgrade
      #
      # Additionally the thrift-compiler version available in standard repos tends to lag
      # the latest release significantly, and so updating to the latest version adds friction
      - dependency-name: "thrift"

      # We want to update arrow and datafusion manually
      - dependency-name: "arrow"
      - dependency-name: "arrow-*"
      - dependency-name: "parquet"
      - dependency-name: "datafusion"
      - dependency-name: "datafusion-*"
  # Before switching to rust-based IOx, influxdb was a Go project which
  # dependabot tracked. After the switch, dependabot would issue alerts for go
  # files that no longer exist. Tell dependabot to ignore "gomod"
  - package-ecosystem: "gomod"
    directory: "/"
    ignore:
      - dependency-name: "*"
