language: go

go:
  - 1.4

install:
  - go get -d -v -t ./... && go build -v ./...
  - go get -u golang.org/x/tools/cmd/vet;
  - go get -u github.com/kisielk/errcheck

script:
    # Put each test command on its own line.
  - go test -timeout 60s -v ./...
  - go tool vet .
  - make errcheck

notifications:
  email:
    on_success: never
    on_failure: change
