language: go

go:
  - 1.1
  - tip

before_install:
  - sudo apt-get update
  - sudo apt-get install -y protobuf-compiler valgrind

install: ./configure
script: make

notifications:
  irc: "chat.freenode.net#influxdb"
  use_notice: false
