version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master

os: Windows Server 2012 R2

# Custom clone folder (variables are not expanded here).
clone_folder: c:\gopath\src\github.com\influxdata\influxdb

# Environment variables
environment:
  GOROOT: C:\go110
  GOPATH: C:\gopath

# Scripts that run after cloning repository
install:
 - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%
 - rmdir c:\go /s /q
 - echo %PATH%
 - echo %GOPATH%
 - cd C:\gopath\src\github.com\influxdata\influxdb
 - go version
 - go env
 - go get github.com/golang/dep/cmd/dep
 - cd C:\gopath\src\github.com\influxdata\influxdb
 - dep ensure -vendor-only

# To run your custom scripts instead of automatic MSBuild
build_script:
 - go get -t -v ./...

before_test:
 - go get github.com/golang/lint/golint

test_script:
 - go test -timeout 15m -v ./...
 - ps: |
    Get-Content .\lint_clean.txt | ForEach-Object { golint $_ } | Tee-Object -Variable lints
    if ($lints) {
        echo $lints | ForEach-Object {
            Add-AppveyorMessage -Message "golint regression $($_.Split(':')[0]) line $($_.Split(':')[1])" -Category "Error" -Details "$_"
        }
        exit 1
    }

# To disable deployment
deploy: off
