[package]
name = "influxdb3_load_generator"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core Crates
observability_deps.workspace = true
trogging.workspace = true

# Local Deps
influxdb3_client = { path = "../influxdb3_client" }

# crates.io Dependencies
serde.workspace = true
clap.workspace = true
dotenvy.workspace = true
humantime.workspace = true
secrecy.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror.workspace = true
url.workspace = true
rand.workspace = true
anyhow.workspace = true
csv.workspace = true
parking_lot.workspace = true
chrono.workspace = true

[lints]
workspace = true
