---
# CI Overview
# -----------
#
# Every commit:
#
# The CI for every PR and merge to main runs tests, fmt, lints and compiles debug binaries
#
# On main if all these checks pass it will then additionally compile in "release" mode and
# publish a docker image to quay.io/influxdb/influxdb3:$COMMIT_SHA
#
# Manually trigger build and push of container image for a branch:
#
# Navigate to https://app.circleci.com/pipelines/github/influxdata/influxdb?branch=<branch-name> (<- change this!)
# Then:
#
# - Click "Run Pipeline" in the top-right
# - Expand "Add Parameters"
# - Add a "boolean" parameter called "release_branch" with the value true
# - Click "Run Pipeline"
#
# You can also do this using the CircleCI API:
#
# Using `xh`:
#
#   # e.g. using 'xh' (https://github.com/ducaale/xh)
#   $ xh -a '<your personal circleCI token>:' POST \
#       https://circleci.com/api/v2/project/github/influxdata/influxdb/pipeline \
#       parameters:='{"release_branch": true}' branch=chore/ci-tidy-up
#
# ...or equivalent with `curl`:
#   $ curl -XPOST -H "Content-Type: application/json" -H "Circle-Token: <your personal circleCI token>" \
#       -d '{"parameters": {"release_branch": true}, "branch": "chore/ci-tidy-up"}' \
#       https://circleci.com/api/v2/project/github/influxdata/influxdb/pipeline

version: 2.1

orbs:
  aws-s3:    circleci/aws-s3@2.0.0
  terraform: circleci/terraform@2.1.0
  rust: circleci/rust@1.6.1

executors:
  linux-amd64:
    machine:
      image: ubuntu-2204:current
      resource_class: 2xlarge
  linux-arm64:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.2xlarge
  darwin:
    resource_class: macos.m1.large.gen1
    macos:
      xcode: 15.0.0
    shell: /bin/bash -eo pipefail
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
      resource_class: windows.2xlarge
    shell: bash.exe -eo pipefail

# Unlike when a commit is pushed to a branch, CircleCI does not automatically
# execute a workflow when a tag is pushed to a repository. These filters
# allow the corresponding workflow to execute on any branch or tag.
any_filter: &any_filter
  filters:
    tags:
      only: /.*/
    branches:
      only: /.*/

release_filter: &release_filter
  filters:
    tags:
      # This regex matches what is found in 'scripts/get-version' with the
      # '[[:digit:]]' transformed into '\d'. This also excludes release
      # candidate detection, because this filter only matches against
      # full releases.
      only: /^v(\d+)(?:\.(\d+))?(?:\.(\d+))?$/
    branches:
      ignore: /.*/

nofork_filter: &nofork_filter
  filters:
    branches:
      ignore: /pull\/[0-9]+/


commands:
  install_rust:

  rust_components:
    description: Verify installed components
    steps:
      - run:
          name: Verify installed components
          command: |
            rustup --version
            rustup show
            cargo fmt --version
            cargo clippy --version

  login_to_gcloud:
    steps:
      - run:
          name: Login to gcloud
          command: |
            echo "${GCLOUD_SERVICE_ACCOUNT_KEY}" >/tmp/gcloud.json
            gcloud auth activate-service-account "${GCLOUD_SERVICE_ACCOUNT_EMAIL}" --key-file /tmp/gcloud.json --quiet
            rm -f /tmp/gcloud.json
            gcloud auth configure-docker us-docker.pkg.dev

jobs:
  fmt:
    docker:
      - image: quay.io/influxdb/rust:ci
    environment:
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - checkout
      - rust_components
      - run:
          name: Rust fmt
          command: cargo fmt --all -- --check
  lint:
    docker:
      - image: quay.io/influxdb/rust:ci
    environment:
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - checkout
      - rust_components
      - run:
          name: Clippy
          command: cargo clippy --all-targets --all-features --workspace -- -D warnings
      - run:
          name: Yamllint
          command: yamllint --config-file .circleci/yamllint.yml --strict .
  cargo-audit:
    docker:
      - image: quay.io/influxdb/rust:ci
    environment:
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    steps:
      - checkout
      - rust_components
      - run:
          name: Install cargo-deny
          command: cargo install cargo-deny
      - run:
          name: cargo-deny Checks
          command: cargo deny check -s
  doc:
    docker:
      - image: quay.io/influxdb/rust:ci
    resource_class: large # use of a smaller executor runs out of memory
    environment:
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      # Turn warnings into errors
      RUSTDOCFLAGS: "-D warnings -A rustdoc::private-intra-doc-links"
    steps:
      - checkout
      - rust_components
      - run:
          name: Cargo doc
          command: cargo doc --document-private-items --no-deps --workspace
      - run:
          name: Compress Docs
          command: tar -cvzf rustdoc.tar.gz target/doc/
      - store_artifacts:
          path: rustdoc.tar.gz

  # Run all tests
  test:
    docker:
      - image: quay.io/influxdb/rust:ci
    resource_class: 2xlarge+ # use of a smaller executor tends crashes on link
    environment:
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUST_BACKTRACE: "1"
    steps:
      - checkout
      - rust_components
      - run:
          name: cargo test --workspace
          command: cargo test --workspace

  # end to end tests with Heappy (heap profiling enabled)
  test-heappy:
    docker:
      - image: quay.io/influxdb/rust:ci
    resource_class: xlarge # use of a smaller executor tends crashes on link
    environment:
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      RUST_BACKTRACE: "1"
    steps:
      - checkout
      - rust_components
      - run:
          name: cargo test --no-default-features --features=heappy end_to_end
          command: cargo test --no-default-features --features=heappy end_to_end

  # Build a dev binary.
  #
  # Compiles a binary with the default ("dev") cargo profile from the influxdb3 source
  # using the latest ci_image (influxdb/rust) and ensures various targets compile successfully
  # Build a dev binary.
  build-dev:
    docker:
      - image: us-east1-docker.pkg.dev/influxdata-team-edge/ci-support/ci-cross-influxdb3:latest
        auth:
          username: _json_key
          password: $CISUPPORT_GCS_AUTHORIZATION
    environment:
      TARGET: << parameters.target >>
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      # The `2xlarge` resource class that we use has 32GB RAM but also 16 CPUs. This means we have 2GB RAM per core on
      # avarage. At peak this is a bit tight, so lower the CPU count for cargo a bit.
      CARGO_BUILD_JOBS: "12"
    parameters:
      target:
        type: string
    steps:
      - checkout
      - run:
          name: Install Target
          command: rustup target add << parameters.target >>
      - run:
          name: Cargo build
          command: target-env cargo build --target=<< parameters.target >> --workspace
      - when:
          condition:
            not:
              equal: [ << parameters.target >>, x86_64-pc-windows-gnu ]
          steps:
          - run:
              name: Check benches compile
              command: target-env cargo check --target=<< parameters.target >> --workspace --benches
          - run:
              name: Check extra features (like prod image)
              command: target-env cargo check --target=<< parameters.target >> --no-default-features --features="aws,gcp,azure,jemalloc_replacing_malloc,tokio_console,pprof"
      - when:
          condition:
            equal: [ << parameters.target >>, x86_64-pc-windows-gnu ]
          steps:
          - run:
              name: Check extra features (like prod image)
              command: target-env cargo check --target=<< parameters.target >> --no-default-features --features="aws,gcp,azure,jemalloc_replacing_malloc,tokio_console"

  # Compile cargo "release" profile binaries for influxdb3 edge releases
  build-release:
    docker:
      - image: us-east1-docker.pkg.dev/influxdata-team-edge/ci-support/ci-cross-influxdb3:latest
        auth:
          username: _json_key
          password: $CISUPPORT_GCS_AUTHORIZATION
    environment:
      TARGET: << parameters.target >>
      # Disable incremental compilation to avoid overhead. We are not preserving these files anyway.
      CARGO_INCREMENTAL: "0"
      # Disable full debug symbol generation to speed up CI build
      # "1" means line tables only, which is useful for panic tracebacks.
      CARGO_PROFILE_DEV_DEBUG: "1"
      # https://github.com/rust-lang/cargo/issues/10280
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
      # The `2xlarge` resource class that we use has 32GB RAM but also 16 CPUs. This means we have 2GB RAM per core on
      # avarage. At peak this is a bit tight, so lower the CPU count for cargo a bit.
      CARGO_BUILD_JOBS: "12"
    parameters:
      target:
        type: string
    steps:
      - checkout
      - run:
          name: Install Target
          command: rustup target add << parameters.target >>
      - run:
          name: Cargo release build
          command: target-env cargo build --target=<< parameters.target >> --workspace --release
          # linking might take a while and doesn't produce CLI output
          no_output_timeout: 30m
  sign-packages:
    circleci_ip_ranges: true
    docker:
      - image: quay.io/influxdb/rsign:latest
        auth:
          username: $QUAY_RSIGN_USERNAME
          password: $QUAY_RSIGN_PASSWORD
    steps:
      - add_ssh_keys:
          fingerprints:
            - fc:7b:6e:a6:38:7c:63:5a:13:be:cb:bb:fa:33:b3:3c
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          for target in /tmp/workspace/artifacts/*
          do
            case "${target}"
            in
              # rsign is shipped on Alpine Linux which uses "busybox ash" instead
              # of bash. ash is somewhat more posix compliant and is missing some
              # extensions and niceties from bash.
              *.deb|*.rpm|*.tar.gz|*.zip)
                rsign "${target}"
              ;;
            esac

            if [ -f "${target}" ]
            then
              # Since all artifacts are present, sign them here. This saves Circle
              # credits over spinning up another instance just to separate out the
              # checksum job.
              sha256sum "${target}" >> "/tmp/workspace/artifacts/influxdb2.${CIRCLE_TAG}.digests"

              # write individual checksums
              md5sum    "${target}" >> "${target}.md5"
              sha256sum "${target}" >> "${target}.sha256"
            fi
          done
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - artifacts
      - store_artifacts:
          path: /tmp/workspace/artifacts
  publish-packages:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync:
          arguments:             --acl public-read
          aws-region:            RELEASE_AWS_REGION
          aws-access-key-id:     RELEASE_AWS_ACCESS_KEY_ID
          aws-secret-access-key: RELEASE_AWS_SECRET_ACCESS_KEY
          from:                  /tmp/workspace/artifacts
          to:                    s3://dl.influxdata.com/influxdb/releases


workflows:
  version: 2
  ci:
    jobs:
      - fmt:
          <<: *any_filter
      - lint:
          <<: *any_filter
      - cargo-audit:
          <<: *any_filter
      - test:
          <<: *any_filter
      - test-heappy:
          <<: *any_filter
      - build-dev:
          <<: *any_filter
          name: build-dev-<< matrix.target >>
          matrix:
            parameters:
              target:
                - aarch64-apple-darwin
                - aarch64-unknown-linux-gnu
                - aarch64-unknown-linux-musl
                - x86_64-pc-windows-gnu
                - x86_64-unknown-linux-gnu
                - x86_64-unknown-linux-musl
      - doc:
          <<: *any_filter
      - build-release:
          # <<: *release_filter
          <<: *any_filter
          name: build-release-<< matrix.target >>
          matrix:
            parameters:
              target:
                - aarch64-apple-darwin
                - aarch64-unknown-linux-gnu
                - aarch64-unknown-linux-musl
                - x86_64-pc-windows-gnu
                - x86_64-unknown-linux-gnu
                - x86_64-unknown-linux-musl
      - sign-packages:
          <<: *release_filter
          requires:
            - build-release
            - test
      - publish-packages:
          <<: *release_filter
          requires:
            - build-release
            - sign-packages
            - test

