version: '2.4'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    healthcheck:
      test: "influx ping"
    restart: always
    ports:
      - 9999:9999
    volumes:
      - influx-cli-configs:/root/.influxdbv2/
  influx_setup:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    restart: "no"
    volumes:
      - influx-cli-configs:/root/.influxdbv2/
      - ./influxdb-setup.bash:/influxdb-setup.bash
    environment:
      INFLUXDB_USER: admin
      INFLUXDB_PASSWORD: 
      INFLUXDB_ORG: influxdata
      INFLUXDB_BUCKET: telegraf
    entrypoint:
      - /influxdb-setup.bash
    depends_on:
      influxdb:
        condition: service_healthy
volumes:
  influx-cli-configs: ~