[package]
name = "tower_trailer"
description = "Allow to send HTTP/2 trailer using a tower layer"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = "0.3"
http = "0.2"
http-body = "0.4"
parking_lot = "0.12"
pin-project = "1.1"
tower = "0.4"
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[dev-dependencies]
