[package]
name = "influxdb3_client"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# crates.io dependencies
bytes.workspace = true
reqwest.workspace = true
secrecy.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
# crates.io dependencies
mockito.workspace = true
tokio.workspace = true

[lints]
workspace = true
